services:
  - type: web
    name: marketing-poster-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash ./.render-start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: GCP_PROJECT_ID
        value: your-gcp-project-id
      - key: GCP_LOCATION
        value: us-central1
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/service-account.json
      - key: GCP_KEY_B64
        sync: false
      - key: VERTEX_IMAGEN_MODEL_GENERATE
        value: imagen-3.0-generate-001
      - key: VERTEX_IMAGEN_MODEL_EDIT
        value: imagen-3.0-edit
      - key: VERTEX_TIMEOUT_SECONDS
        value: "60"
      - key: VERTEX_SAFETY_FILTER_LEVEL
        value: block_some
      - key: VERTEX_SEED
        value: "0"
