name: guard-module-sanity
on: [push, pull_request]
jobs:
  grep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Forbid legacy guard module path
        run: |
          set -e
          ! git grep -n "app.middlewares.huge_or_b64_guard" -- '*.py' || (echo "Use app.middlewares.reject_huge_or_base64 instead"; exit 1)
